In [77]:
# Vacuum Cleaner Agent - This agent has no percept sequence
import numpy as np
import random
# The Vacuum Cleaner is given the following 3 states:
# Switch Location, Idle and Suck
StatesCleaned = 0
Battery = 150
counter = 0
# Array simulates a 10x10 room
Room = np.array([[1,1,1,2,1,1,1,1,2,1], [1,2,0,1,0,1,2,0,1,0], [0,0,1,1,0,0,0,1,1,0], 
                 [1,1,2,1,0,1,1,2,1,0], [2,0,0,0,1,2,0,0,0,1],[1,1,1,2,1,1,1,1,2,1], 
                 [1,2,0,1,0,1,2,0,1,0], [0,0,1,1,0,0,0,1,1,0], [1,1,2,1,0,1,1,2,1,0], 
                 [2,0,0,0,1,2,0,0,0,1]])
# 0 = Clean, 1 = Dirty, 2 = Unknown

def SwitchLocation():
  global Battery
  global counter
  x, y = NewCoordinates()
  Battery -= 1
  counter = 0
  print('Switch Location')
  AgentFunction(x, y)

def Suck(x, y):
  global Battery
  global StatesCleaned
  Room[x][y] = 0
  Battery -= 1
  print('Suck')
  StatesCleaned += 1
  AgentFunction(x, y)

def Idle(x, y):
  global counter
  if (counter == 1):
    print('Idle')
    AgentFunction(x,y)
  elif (counter != 1):
    SwitchLocation()

def NewCoordinates():
  StartingPoint1 = random.randint(0,9)
  StartingPoint2 = random.randint(0,9)
  return StartingPoint1, StartingPoint2

def AgentFunction(x, y):
  global counter
  global Battery
  if (Battery > 0):

    if (Room[x][y] == 1):

      Suck(x, y)

    elif (Room[x][y] == 0 or Room[x][y] == 2):

      counter += 1
      Idle(x, y)

  else: 
    print('\n')
    print('Vacuum Cleaner ran out of Battery')
    print('Final Room: ')
    print(Room)
    print('States Cleaned: ' + str(StatesCleaned))
    
def main():
  print('Starting Room: ')
  print(Room)
  print('\n')
  x, y = NewCoordinates()
  AgentFunction(x, y)

main()


Starting Room: 
[[1 1 1 2 1 1 1 1 2 1]
 [1 2 0 1 0 1 2 0 1 0]
 [0 0 1 1 0 0 0 1 1 0]
 [1 1 2 1 0 1 1 2 1 0]
 [2 0 0 0 1 2 0 0 0 1]
 [1 1 1 2 1 1 1 1 2 1]
 [1 2 0 1 0 1 2 0 1 0]
 [0 0 1 1 0 0 0 1 1 0]
 [1 1 2 1 0 1 1 2 1 0]
 [2 0 0 0 1 2 0 0 0 1]]


Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Locatio

In [80]:
# Vacuum Cleaner Agent - has a Percept Sequence and references it.
import numpy as np
import random
# The Vacuum Cleaner is given the following 3 states:
# Switch Location, Idle and Suck
PerceptSequence = []
StatesCleaned = 0
Battery = 150
counter = 0
# Array simulates a 10x10 room
Room = np.array([[1,1,1,2,1,1,1,1,2,1], [1,2,0,1,0,1,2,0,1,0], [0,0,1,1,0,0,0,1,1,0], 
                 [1,1,2,1,0,1,1,2,1,0], [2,0,0,0,1,2,0,0,0,1],[1,1,1,2,1,1,1,1,2,1], 
                 [1,2,0,1,0,1,2,0,1,0], [0,0,1,1,0,0,0,1,1,0], [1,1,2,1,0,1,1,2,1,0], 
                 [2,0,0,0,1,2,0,0,0,1]])
# 0 = Clean, 1 = Dirty, 2 = Unknown

def SwitchLocation():
  global Battery
  global counter
  x, y = NewCoordinates()
  Battery -= 1
  counter = 0
  print('Switch Location')
  AgentFunction(x, y)

def Suck(x, y):
  global Battery
  global StatesCleaned
  Room[x][y] = 0
  Battery -= 1
  print('Suck')
  StatesCleaned += 1
  AgentFunction(x, y)

def Idle(x, y):
  global counter
  if (counter == 1):
    print('Idle')
    AgentFunction(x,y)
  elif (counter != 1):
    PerceptSequence.append(str(x)+str(y))
    SwitchLocation()

def ConsultPerceptSequence(x, y):
  global PerceptSequence
  z = str(x)+str(y)
  #print(z)
  #print(PerceptSequence)
  if z in PerceptSequence:
    return False
  else:
    return True

def NewCoordinates():
  global Battery
  checking = False
  whileLoopCounter = 0
  while (checking == False):
    StartingPoint1 = random.randint(0,9)
    StartingPoint2 = random.randint(0,9)
    checking = ConsultPerceptSequence(StartingPoint1, StartingPoint2)
    if (checking == False):
      whileLoopCounter += 1
      # This loop Counter is checking 300 times to make sure it has randomly
      # landed on every spot in the Room and checked it against the Percept
      # Sequence.  There is still room for error here. (Even though it's checking
      # 300 times, it could still miss a coordinate where it's dirty.)
      if (whileLoopCounter >= 300):
        checking = True
        Battery = -100
  return StartingPoint1, StartingPoint2


def AgentFunction(x, y):
  global counter
  global PerceptSequence
  global StatesCleaned
  global Battery

  if (Battery > 0):

    if (Room[x][y] == 1):

      Suck(x, y)

    elif (Room[x][y] == 0 or Room[x][y] == 2):
      
      counter += 1
      Idle(x, y)
  
  elif (Battery == -101):
    print('\n')
    print('Percept Sequence (Final): ')
    print(PerceptSequence)
    print('Final Room: ')
    print(Room)
    print('\n')
    print('Vacuum Cleaner Cleaned entire room!')
    print('States Cleaned: ' + str(StatesCleaned))
    print('Battery Level: ' + str(Battery))

  else: 
    print('\n')
    print('Percept Sequence (Final): ')
    print(PerceptSequence)
    print('Final Room: ')
    print(Room)
    print('\n')
    print('Vacuum Cleaner ran out of Battery')
    print('States Cleaned: ' + str(StatesCleaned))
    
def main():
  print('Percept Sequence (Starting): ')
  print(PerceptSequence)
  print('Starting Room: ')
  print(Room)
  print('\n')

  x, y = NewCoordinates()
  AgentFunction(x, y)

main()


Percept Sequence (Starting): 
[]
Starting Room: 
[[1 1 1 2 1 1 1 1 2 1]
 [1 2 0 1 0 1 2 0 1 0]
 [0 0 1 1 0 0 0 1 1 0]
 [1 1 2 1 0 1 1 2 1 0]
 [2 0 0 0 1 2 0 0 0 1]
 [1 1 1 2 1 1 1 1 2 1]
 [1 2 0 1 0 1 2 0 1 0]
 [0 0 1 1 0 0 0 1 1 0]
 [1 1 2 1 0 1 1 2 1 0]
 [2 0 0 0 1 2 0 0 0 1]]


Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Locati