In [68]:
# Vacuum Cleaner Agent
import numpy as np
import random
# The Vacuum Cleaner is given the following 3 states:
VacuumCleaner = ['Switch Location', 'Suck', 'Idle']
PerceptSequence = ['(1,4)']
Battery = 50
counter = 0
# Array simulates a 5x5 room
Room = np.array([[1,1,1,2,1], [1,2,0,1,0], [0,0,1,1,0], [1,1,2,1,0], [2,0,0,0,1]])
# 0 = Clean, 1 = Dirty, 2 = Unknown

def SwitchLocation():
  global Battery
  global counter
  x, y = NewCoordinates()
  Battery -= 1
  counter = 0
  print('Switch Location')
  AgentFunction(x, y)

def Suck(x, y):
  global Battery
  Room[x][y] = 0
  Battery -= 1
  print('Suck')
  AgentFunction(x, y)

def Idle(x, y):
  global counter
  if (counter == 1):
    print('Idle')
    AgentFunction(x,y)
  elif (counter != 1):
    SwitchLocation()

def NewCoordinates():
  StartingPoint1 = random.randint(0,4)
  StartingPoint2 = random.randint(0,4)
  return StartingPoint1, StartingPoint2

def AgentFunction(x, y):
  global counter
  if (Battery > 0):

    if (Room[x][y] == 1):

      Suck(x, y)

    elif (Room[x][y] == 0 or Room[x][y] == 2):

      counter += 1
      Idle(x, y)

  else: 
    print('Vacuum Cleaner ran out of Battery')
    print('Final Room: ')
    print(Room)
    
def main():
  print('Starting Room: ')
  print(Room)
  x, y = NewCoordinates()
  AgentFunction(x, y)

main()









Starting Room: 
[[1 1 1 2 1]
 [1 2 0 1 0]
 [0 0 1 1 0]
 [1 1 2 1 0]
 [2 0 0 0 1]]
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Suck
Idle
Switch Location
Suck
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Idle
Switch Location
Vacuum Cleaner ran out of Ba